[general]
live_config_reload = true

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#242933"

[colors.normal]
black = "#242933"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#d8dee9"
yellow = "#ebcb8b"

[colors.primary]
background = "#242933"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#242933"

[env]
COLORTERM = ""

[font]
size = 15.0

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
title = "Alacritty"
option_as_alt = "Both"

[window.padding]
x = 6
y = 4
