[general]
live_config_reload = true
import = ["themes/alacritty.toml"]

[env]
COLORTERM = ""

[font]
size = 15.0

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
title = "Alacritty"
option_as_alt = "Both"

[window.padding]
x = 6
y = 4
